# Generated by Django 4.0.3 on 2022-03-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='teacher',
            new_name='classroom_id',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='material',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_user', to='vis.classroomuser'),
        ),
    ]
