# Generated by Django 4.0.3 on 2022-03-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_rename_teacher_material_classroom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
        migrations.AlterField(
            model_name='material',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classroom_id', to='vis.classroom'),
        ),
    ]
