# Generated by Django 4.0.3 on 2022-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0003_remove_classroom_user_alter_material_classroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classroomuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
