# Generated by Django 4.0.2 on 2022-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0006_alter_classroom_id_alter_classroomuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='id_school',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
